
- include: create.yml
  when: windows_servers.join_domain == "1" and general.cloud_provider != "local"

- include: create_local.yml
  when: windows_servers.join_domain == "1" and general.cloud_provider == "local"

- include: windows-disable-firewall.yml
  when: windows_servers.join_domain == "1"