
name: release
on:
  push:
    tags:
      - "v*.*.*"
env:
  IMAGE_NAME: "splunk/attack_range"

jobs:
  publish-github-release:
    runs-on: ubuntu-latest
    needs: [validate-tag-if-present]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            ref: 'develop'

        - name: Set tag
          id: vars
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

        - name: Prepare Release for Publishing on github
          run: |
            cd ..
            tar -zcvf attack-range-${{ steps.vars.outputs.tag }}.tar.gz attack_range
            sha256sum attack-range-${{ steps.vars.outputs.tag }}.tar.gz > checksum-${{ steps.vars.outputs.tag }}.txt

        - name: Upload Release Artifacts
          uses: softprops/action-gh-release@v2
          with:
            files: |
              ../attack-range-${{ steps.vars.outputs.tag }}.tar.gz
              ../checksum-%{{ steps.vars.outputs.tag }}.txt
  
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'develop'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: splunk/attack_range         
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}